### ISSUE TITLE
Move Arduino libraries dedicated for STM32 core into single repo

### ISSUE THREAD

**Issue by fpistm** [stm32duino/Arduino_Core_STM32#48]
Purpose of this issue is to move Arduino libraries dedicated for STM32 core in separate repository.

I talk about libraries dedicated to hardware features: on board SD, Ethernet, LCD….
For purely software libraries, pull request should be done on dedicated github (ex: firmata,…) as far as possible else a repo could be created.

The core should only embed those for common hardware support (Wire/SPI/…).
As specified here:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager
So one library == a single repo.

- [x] SD required 2 repos: 
- [FatFs](https://github.com/stm32duino/FatFs): _available through the Arduino Library manager_
- [STM32SD](https://github.com/stm32duino/STM32SD): _available through the Arduino Library manager_
- [x] NativeEthernet required 2 repos:
- [LwIP](https://github.com/stm32duino/LwIP): _available through the Arduino Library manager_
- [STM32Ethernet](https://github.com/stm32duino/STM32Ethernet): _available through the Arduino Library manager_
- [x] Firmata:  STM32 support added in [Firmata 2.5.7](https://github.com/firmata/arduino/releases/tag/2.5.7)
- [x] CapacitiveSensor-0.5.1 to do on related github --> https://github.com/PaulStoffregen/CapacitiveSensor/pull/30
- [x] EEPROM; based on V2.0.0. Kept in the core as specific to the architecture "stm32". Only header modified.
- [x] GSM: Removed. See #331
- [x] LiquidCrystal; Use official one. See #77
- [x] Mouse & Keyboard: separated repo? --> kept as built-in library as USB dependent.
- [x] Servo: reworked thanks #102. [PR](https://github.com/arduino-libraries/Servo/pull/10) done on official Library: [arduino-libraries/Servo](https://github.com/arduino-libraries/Servo)
- [x] TFT: pull request done and merged on related github --> [arduino-libraries/TFT#11](https://github.com/arduino-libraries/TFT/pull/11). Moreover, [Ucglib_Arduino](https://github.com/olikraus/Ucglib_Arduino) could be used and manage more displays than the ST7735.
- [x] WiFi: Use official one even if shield retired

**ARDUINO_ARCH_STM32** must be used as differentiator.

This is a first approach any comments/suggestions are welcome. Mainly on repo name or way of working.

**Comment by Testato** [comment]
in my opinion open a repo for every library it is dispersive, 
The lib can remain here, in a separate folder, the important think is that all library, in the file library.proprietry, change it's name from the arduino original name. Because the ArduinoIDE have problem on update when two lib have same name.

For example it is enough call the Wire library "Wire(STM32)"

**Comment by fpistm** [comment]
Firmata need an update, I will do the pull request on the official repo to add support for the STM32 then I will delete it from the core.

Open a repo for each specific library allow to use Library manager from Arduino. Having all libraries in the core is not a good option. Many libraries are specific to a board (ex: ethernet is available only on few boards (F429zi, Disco746)) so this will increase core size while user will not use it. If user wants then he will have the possibility to install it.

**Comment by Testato** [comment]
It is true that you do not have ide library update, but if the lib is in the core it will updated when update the core by board manager, may be some modification on a lib needed by a core modification, in this case you can go out of sync.

Very big core peoject, like ESP, have it's modified lib inside the core. Another useful think is that when the libs is in the core you can immediately view how many lib you have so what you can do, without search for a lib without cechk if it is compatible.

But i know that also the separated github have advantage, like tracking of issue directly to a lib repo, instead of all togheter on the core repo

**Comment by fpistm** [comment]
PR for Firmata merged in official repo.
Wainting new release version before removing it from the core.

**Comment by fpistm** [comment]
Release of [Firmata 2.5.7](https://github.com/firmata/arduino/releases/tag/2.5.7) available.

**Comment by fpistm** [comment]
TFT: pull request done: [arduino-libraries/TFT#11](https://github.com/arduino-libraries/TFT/pull/11)
Required #90

**Comment by straccio** [comment]
Another libraries could be: 
- OneWire (based on HAL) 
- FreeRTOS (that's will be awesome)
- WolfSSL (really useful for IoT projects)

**Comment by fpistm** [comment]
Right @straccio,
there's many libraries which could be fine to test/port.
This issue was opened for the one which was included in the core (built-in) at its beginning not to request some new library porting ;)

**Comment by straccio** [comment]
Ok, Sorry!
but FreeRTOS is inside the stm32CubeFW ^^
Anyway i'll working on these libraries in the near future!

**Comment by fpistm** [comment]
No worries ;)
